-- MySQL Script generated by MySQL Workbench
-- 05/11/16 17:23:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Database genindexe
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `genindexe`;

-- -----------------------------------------------------
-- Database genindexe
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `genindexe`;

-- -----------------------------------------------------
-- Table `genindexe`.`Analysis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genindexe`.`Analysis` ;

CREATE TABLE IF NOT EXISTS `genindexe`.`Analysis` (
  `Analysis_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Analysis_Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genindexe`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genindexe`.`Customer` ;

CREATE TABLE IF NOT EXISTS `genindexe`.`Customer` (
  `Customer_Id` INT NOT NULL AUTO_INCREMENT,
  `Customer_Name` VARCHAR(45) NOT NULL,
  `Customer_Town` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Customer_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genindexe`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genindexe`.`Order` ;

CREATE TABLE IF NOT EXISTS `genindexe`.`Order` (
  `Order_Id` INT NOT NULL AUTO_INCREMENT,
  `Order_Status` VARCHAR(45) NOT NULL,
  `Analysis_Name` VARCHAR(45) NOT NULL,
  `Customer_Id` INT NOT NULL,
  PRIMARY KEY (`Order_Id`),
  INDEX `fk_order_analysis_idx` (`Analysis_Name` ASC),
  INDEX `fk_order_customer_idx` (`Customer_Id` ASC),
  CONSTRAINT `fk_order_analysis`
    FOREIGN KEY (`Analysis_Name`)
    REFERENCES `genindexe`.`Analysis` (`Analysis_Name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_customer`
    FOREIGN KEY (`Customer_Id`)
    REFERENCES `genindexe`.`Customer` (`Customer_Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genindexe`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genindexe`.`Category` ;

CREATE TABLE IF NOT EXISTS `genindexe`.`Category` (
  `Category_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Category_Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genindexe`.`Specie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genindexe`.`Specie` ;

CREATE TABLE IF NOT EXISTS `genindexe`.`Specie` (
  `Specie_Name` VARCHAR(45) NOT NULL,
  `Category_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Specie_Name`),
  INDEX `fk_specie_category_idx` (`Category_Name` ASC),
  CONSTRAINT `fk_specie_category`
    FOREIGN KEY (`Category_Name`)
    REFERENCES `genindexe`.`Category` (`Category_Name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genindexe`.`Sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genindexe`.`Sample` ;

CREATE TABLE IF NOT EXISTS `genindexe`.`Sample` (
  `Sample_Id` INT NOT NULL AUTO_INCREMENT,
  `Specie_Name` VARCHAR(45) NOT NULL,
  `Order_Id` INT NOT NULL,
  PRIMARY KEY (`Sample_Id`),
  INDEX `fk_sample_specie_idx` (`Specie_Name` ASC),
  INDEX `fk_sample_order_idx` (`Order_Id` ASC),
  CONSTRAINT `fk_sample_specie`
    FOREIGN KEY (`Specie_Name`)
    REFERENCES `genindexe`.`Specie` (`Specie_Name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sample_order`
    FOREIGN KEY (`Order_Id`)
    REFERENCES `genindexe`.`Order` (`Order_Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genindexe`.`Relevant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genindexe`.`Relevant` ;

CREATE TABLE IF NOT EXISTS `genindexe`.`Relevant` (
  `Specie_Name` VARCHAR(45) NOT NULL,
  `Analysis_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Specie_Name`, `Analysis_Name`),
  INDEX `fk_relevant_analysis_idx` (`Analysis_Name` ASC),
  CONSTRAINT `fk_relevant_specie`
    FOREIGN KEY (`Specie_Name`)
    REFERENCES `genindexe`.`Specie` (`Specie_Name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_relevant_analysis`
    FOREIGN KEY (`Analysis_Name`)
    REFERENCES `genindexe`.`Analysis` (`Analysis_Name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
